### ISSUE TITLE
Unexpected ImageTypeError

### ISSUE THREAD

**Issue by braznaavtrav** [HumbleSoftware/js-imagediff#27]
I am using jasmine (running from grunt) to test the diff between an image and canvas object and getting an unexpected `ImageTypeError: Submitted object was not an image.` when running `toImageDiffEqual`. 

To make sure the objects I am passing into `toImageDiffEqual` are actual Image objects I tried testing them with `isImage` like so:

    expect(imagediff.isImage($img[0])).toBe(true);

which passes. 

When I try testing the `$img[0]` against itself in `toImageDiffEqual` like so:

    expect($img[0]).toImageDiffEqual($img[0]);

I get the `ImageTypeError`.

Any idea what I could be doing wrong here?

**Comment by cburgmer** [comment]
Closing this for now. If this is still an issue please reopen.
