### ISSUE TITLE
Use of imagediff with Jasmine / Karma / RequireJS

### ISSUE THREAD

**Issue by mstefaniuk** [HumbleSoftware/js-imagediff#46]
I have project divided into modules handled with RequireJS. I would like to use imagediff as Jasmine matcher but currently I cannot load it properly. Loading it with RequireJS / `define()` results with
```
TypeError: '[object Object]' is not a constructor (evaluating 'new Canvas()')
  at D:/Tools/d3js-dot/lib/js-imagediff/imagediff.js:39
```
It is because `define()` is calls `definition` with own arguments where third (as `Canvas` expected) is an object with some metadata.

One and only way to make it running is to replace `canvas = Canvas ?` with `canvas = !window && Canvas ?` to skip wrong parameter.

**Comment by mstefaniuk** [comment]
I prepared slightly different patch for initialization via `define()`. Please check #47.

**Comment by albuch** [comment]
+1

**Comment by cburgmer** [comment]
I just merged the changes. Thanks a lot for that. Sorry for the long delay. We should properly do a next soonish.
