### ISSUE TITLE
Can't get this to work with jasmine (2.1.3) in browser 

### ISSUE THREAD

**Issue by hayesmaker** [HumbleSoftware/js-imagediff#48]
image loaded Object {class: SymbolWinsComponent, stage: Stage, g: Graphics} img src=​"favicon-16x16.png"
imagediff.js:270 Uncaught #<Object>checkType @ imagediff.js:270imagediff.equal @ imagediff.js:374jasmine.toImageDiffEqual @ imagediff.js:333Expectation.wrapCompare @ jasmine.js:1331img.onload @ SymbolWinsComponentSpec.js:26

my test fails always fails see the comment below:

 // Validation
  function checkType () {
    var i;
    for (i = 0; i < arguments.length; i++) {
      if (!isImageType(arguments[i])) {
        throw { //###### < ERROR THROWN #######
          name : 'ImageTypeError',
          message : 'Submitted object was not an image.'
        };
      }
    }
  }

below is my test:

	beforeEach(function () {
		this.class = new G.SymbolWinsComponent();
		jasmine.addMatchers(imagediff.jasmine);

		this.stage = new createjs.Stage(imagediff.createCanvas(116, 103));
		var self = this;

		compareImage = function (path, done, expect, pixelTolerance) {
			//var stage = this.stage;
			self.stage.update();

			var img = new Image();
			img.src = path;
			img.onload = function () {
				var pixels = this.width * this.height;
				var tolerance = pixels * (typeof pixelTolerance === 'undefined' ? 0.005 :   pixelTolerance);

				console.log('image loaded', self, this);

				expect(self.stage.canvas).toImageDiffEqual(this, tolerance); //###### < ERROR THROWN #######
				done();
			};
			img.onerror = function(){
				fail(img.src + ' failed to load');
				done();
			};
		};

	it("Correct M1 animation frame 000 is shown", function(done) {

		var shape = new createjs.Shape();
		this.g = shape.graphics;
		this.stage.addChild(shape);
		this.g.setStrokeStyle(2);
		this.g.beginStroke(this.sColor);
		this.g.beginFill(this.fColor);
		this.g.moveTo(120, 100).arc(100, 100, 20, 0, Math.PI);

		compareImage("/javascripts/test/assets/m1-sprite__000.png", done, expect, 0.01);

	});

**Comment by cburgmer** [comment]
imagediff in version 1.0.8 supports Jasmine 1.x while the yet unreleased v1.1 branch supports jasmine 2.0. 

Can you try and state whether the branch works for you?

**Comment by hayesmaker** [comment]
Yes! Thank you, v1.1 is good :+1:
